name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libsqlite3-dev libgdbm-dev libssl-dev libbz2-dev libffi-dev build-essential
          pip install --user --upgrade buildozer cython virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer init
          
          # Litsenziyani qabul qilishni majburlash
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          
          # Tizimga litsenziyalar qabul qilinganini oldindan bildirib qo'yish
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          mkdir -p "$HOME/.buildozer/android/platform/android-sdk/licenses"
          echo -e "24a0d50578307281920263a74d29524fcc39e868\n84831b9409646a918e30573bab4c9c91346d8abd\n504667f4c0de7af1a06de9f4b1727b84351f2910" > "$HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license"
          
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
